### ISSUE TITLE
ERROR undefined method `why' for #<ContactValidator>

### ISSUE THREAD

**Issue by gbp** [mysociety/whatdotheyknow-theme#1674]
```
An ActionView::Template::Error occurred in help#contact:

  undefined method `why' for #<ContactValidator:0x00007f4a20fe5648 ...snip... @errors=#<ActiveModel::Errors []>>
  lib/themes/whatdotheyknow-theme/lib/views/help/_contact_volunteer_form.html.erb:28


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/help/contact
  * HTTP Method: POST
  * IP address : ...snip...
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"...snip...", "contact"=>{"understand"=>"1", "subject"=>"...snip...", "message"=>"...snip...", "comment"=>""}, "remove"=>"remove", "current_form"=>"wdtk", "submitted_contact_form"=>"1", "controller"=>"help", "action"=>"contact"}
  * Timestamp  : 2023-05-03 23:04:15 +0100
  * Process: 244692

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"...snip...",
   "locale"=>"en",
   "remember_me"=>false,
   "user_id"=>...snip...,
   "user_login_token"=>"...snip...",
   "post_redirect_token"=>"...snip...",
   "ttl"=>"2023-05-03T23:03:43.013+01:00",
   "_csrf_token"=>"...snip..."}

-------------------------------
Backtrace:
-------------------------------

  lib/themes/whatdotheyknow-theme/lib/views/help/_contact_volunteer_form.html.erb:28
  lib/themes/whatdotheyknow-theme/lib/views/help/_contact_volunteer_form.html.erb:1
  lib/themes/whatdotheyknow-theme/lib/views/help/contact.html.erb:129
  app/controllers/application_controller.rb:111:in `record_memory'
  lib/deeply_nested_params.rb:15:in `call'
  lib/strip_empty_sessions.rb:14:in `call'
```

**Comment by gbp** [comment]
Happening when the `Remove` button in the "Include link to request" section is used.
